version: '2'

services:

  #ldap:
  #  extends:
  #    file: docker-compose-common.yml
  #    service: ldap

  mysql:
    extends:
      file: docker-compose-common.yml
      service: mysql

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis

  celerybeat:
    extends:
      file: docker-compose-common.yml
      service: admin-develoment
    command: celery -A labcomp beat
    depends_on:
      - mysql
      - redis

  celeryworker:
    extends:
      file: docker-compose-common.yml
      service: admin-develoment
    command: celery -A labcomp worker
    depends_on:
      - mysql
      - redis

  django:
    extends:
      file: docker-compose-common.yml
      service: admin-develoment
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - mysql
      - redis
    ports:
      - '8000:8000'
